# Generated by Django 2.2.1 on 2019-07-21 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AideCan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('date', models.DateTimeField()),
                ('time', models.DurationField()),
                ('typem', models.CharField(choices=[('Mammography', 'M'), ('Numirique', 'N')], max_length=25)),
                ('file', models.FileField(upload_to='mod/', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='background_tissue',
            field=models.CharField(choices=[('F', 'Fatty'), ('G', 'Fatty-glandular'), ('D', 'Dense-glandular')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='date',
            field=models.DateField(default=datetime.date(2019, 7, 21)),
        ),
    ]
